spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/itripdb?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password:
    database: 0
    jedis:
      pool:
        min-idle: 2
        max-idle: 8
        max-active: 8
        max-wait: 100
mybatis:
  mapper-locations: classpath:cn/itrip/dao/**/*.xml
  type-aliases-package: cn.trip.beans
